### ISSUE TITLE
Setup IAM accounts and policies for AWS.

### ISSUE THREAD

**Issue by chrislgarry** [Federated-Reserve/Operations#4]
Setup AWS IAM accounts for each engineer. Federated servers and others will be shared resources that everyone can see via modifying IAM policies to all it. Then, everything else will be private, so users can have their own workspace to practice without cluttering production server console.

https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html

**Comment by jmartinez10** [comment]
1. ) AWS IAM Accounts have been created for each engineer.
2.) IAM Policy has been built with Full Access on services EC2 and S3.

**Comment by chrislgarry** [comment]
Copy pasta from the discord:

Hmmm will probably need more access. It’s ok to give full access to everything.
And then tighten up access after we have set everything up. Regarding usernames, we should probably use our last names to be consistent. User handles may change, or as team grows, maybe hard to know who is who. Sorry was a bit slow about responding to that question.
But otherwise looks good!

**Comment by chrislgarry** [comment]
Is this done?

**Comment by jmartinez10** [comment]
Yes

**Comment by chrislgarry** [comment]
Cool. Have you tested out logging into your IAM and accessing various resources. Hmm we should probably wait to close this issue until everyone confirms. Ill test my IAM today.

**Comment by chrislgarry** [comment]
Gotta close these in addition to moving them to the DONE column.
